version: "3.0"
services:
 springapp:
   images: bhuvaneswaribhoopal/springboot-app-docker:VERSION
   ports:
   - 8080:8080
   environments:
   - MONGO_DB_HOSTNAME=mongo
   - MONGO_DB_USERNAME=devdb
   - MONGO_DB_PASSWORD=db@123
   networks:
   - springappnetwork
 mongo:
    image: mongo
    volumes:
    - mongovol:/data/db
    environments:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=db@123
networks:
  springappbridge:
    driver: bridge
volumes: 
  mongovol:
    driver: local
